// !! STATUS CAN BE: ACTIVE, INACTIVE, ADMIN MANDATED, REPEALED, BY-CONVICTION

const TITLES_DATA = [
  {
    name: 'Title 1 - Criminal Code',
    color: '#60705b23',
    chapters: [
      {
        name: 'SUBTITLE 1 - OFFENSES AGAINST THE PUBLIC',
        subchapters: [
          {name: 'Chapter I - Offenses Against the State & Public Order',
            provisions: [
              { 
                sec: '1 F.S.C. § 1101', 
                title: 'Unauthorized distribution of classified information', 
                text: 'Any person who knowingly and willfully distributes, or otherwise makes available to an unauthorized person, or uses in any manner prejudicial to the safety or interest of the State or for the benefit of any foreign government any classified or military information shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { 
                sec: '1 F.S.C. § 1102', 
                title: 'Inciting a Riot', 
                text: 'Any person who urges, provokes, or encourages a group of three or more individuals to engage in a public disturbance involving violence, damage to property, or a clear and present danger to public safety shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1103', 
                title: 'Rioting', 
                text: 'Any person who knowingly participates in a public disturbance involving an assemblage of FOUR or more persons, and who engages in conduct that creates a substantial risk of or results in injury to persons, damage to property, or the imminent threat thereof, and who acts with the common intent to commit an unlawful act or to accomplish a lawful purpose by unlawful means, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1104', 
                title: 'Treason', 
                text: 'Any person who levies war against the State, adheres to its enemies, or provides them with aid, comfort, or intelligence with the intent to overthrow or undermine the legitimate government shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1105', 
                title: 'Criminal Anarchy', 
                text: 'Any person who advocates, by written or verbal means, the overthrow or destruction of the State government by force, violence, or other unlawful means shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1106', 
                title: 'Abuse of State Flag or Insignia', 
                text: 'Any person who knowingly and publicly mutilates, defaces, or desecrates the State flag, seal, or official insignia with the intent to show contempt or ridicule the State shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1107', 
                title: 'Espionage', 
                text: 'Any person who distributes, or attempt to distribute, classified information to foreign governments, with intent or reason to believe that it is to be used to the injury of the State of Mayflower or advantage of a foreign government shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1108', 
                title: 'Unlawful Assembly Against the State', 
                text: 'Any individual who knowingly gathers, conspires, or participates in an assembly with the purpose of violently opposing, obstructing, or overthrowing the lawful government of the State of Fairmont shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1109', 
                title: 'Disorderly Conduct', 
                text: 'Any person who knowingly engages in violent, abusive, indecent, profane, boisterous, unreasonably loud, or otherwise disorderly conduct that tends to cause or provoke a public disturbance, breach of the peace, or public alarm, or who knowingly acts in a manner that unreasonably interferes with the comfort, peace, or safety of another person, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1110', 
                title: 'Disturbing the Peace', 
                text: 'Any person who knowingly makes or causes to be made any unreasonable, loud, or excessive noise, or who engages in any fight, brawl, tumultuous conduct, or other activity that disturbs the peace, quiet, or tranquility of any neighborhood, dwelling, or public place, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1111', 
                title: 'Loitering', 
                text: 'Any person who knowingly remains in a public place or upon the premises of another without a lawful purpose, and who engages in conduct that creates a reasonable fear of harm or annoyance to others, after having been notified by a law enforcement officer or property owner to depart, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1112', 
                title: 'Harboring a Fugitive', 
                text: 'Any person who knowingly conceals, harbors, or provides assistance to a person with the intent to prevent their lawful apprehension, arrest, or prosecution, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
            ],
          },
          {name: 'Chapter II - Offenses Involving Records and Documentation',
            provisions: [
              { 
                sec: '1 F.S.C. § 1201', 
                title: 'Forgery', 
                text: 'Any person who knowingly alters, creates, or counterfeits any official state document, license, permit, identification card, or currency with the intent to deceive or defraud the State or its citizens shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { 
                sec: '1 F.S.C. § 1202', 
                title: 'Tampering with Public Records', 
                text: 'Any person who knowingly destroys, mutilates, conceals, or removes any public record or document with the intent to impede its function, alter its contents, or prevent its use as evidence shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1203', 
                title: 'False Impersonation', 
                text: 'Any person who knowingly assumes the identity of another individual, particularly a public official or state employee, with the intent to deceive a government entity, gain unauthorized access, or obtain a benefit shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1204', 
                title: 'Falsifying Business Records', 
                text: 'Any person who makes or causes a false entry in the business records of any entity with the intent to defraud the State, evade a tax, or conceal a crime shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
            ]
          },

          {name: 'Chapter III - Offenses Relating to Public Service',
            provisions: [
              { 
                sec: '1 F.S.C. § 1301', 
                title: 'Obstruction of Justice', 
                text: 'Any person who knowingly influences, obstructs, or impedes the administration of justice or the due execution of the law, including tampering with witnesses or jurors, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { 
                sec: '1 F.S.C. § 1302', 
                title: 'Bribery', 
                text: 'Any person who offers, gives, or promises any benefit, money, or item of value to a public servant with the intent to influence their official action, vote, opinion, judgment, or discretion shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1303', 
                title: 'Aiding Escape or Unlawful Release', 
                text: 'Any person, including a public servant, who knowingly assists, conceals, or facilitates the escape of an individual in lawful custody, or who releases a prisoner without proper legal authority, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1304', 
                title: 'Perjury', 
                text: 'Any person who makes a false sworn statement or affirmation in an official proceeding, including a trial, deposition, or formal investigation, regarding a material matter shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1305', 
                title: 'Felony Misconduct', 
                text: 'Any person who, with corrupt intent, abuses or misuses their position, as defined by law, to obtain a personal benefit for themselves or for another, or who engages in conduct that results in a threat to life or public safety, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1306', 
                title: 'Gross Misconduct', 
                text: 'Any person who intentionally and immorally abuses their position, as defined by law, with corrupt intent, where such abuse does not result in a threat to life or public safety, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1307', 
                title: 'Misconduct', 
                text: 'Any person who unintentionally and improperly abuses their official position, as defined by law, to gain any benefit for themselves or for their associates shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1308', 
                title: 'Impersonation of a Public Servant', 
                text: 'Any person who knowingly assumes, pretends to hold, or exercises the duties of a public office or law enforcement position without being duly authorized, commissioned, or appointed to do so, with the intent to deceive or gain an unlawful benefit, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1309', 
                title: 'Dereliction of Duty', 
                text: 'Any public servant who knowingly and willfully fails or refuses to perform a duty required by law, ordinance, or departmental regulation, or who abandons their post or assigned responsibilities without proper authorization, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1310', 
                title: 'Embezzlement of Public Funds', 
                text: 'Any public servant who, being entrusted with the custody, control, or management of state funds, property, or assets, knowingly converts, misappropriates, or transfers such funds or assets to their own use or the use of another without legal authorization shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1311', 
                title: 'Failure to Comply', 
                text: 'Any person who willfully fails or refuses to comply with any lawful order or direction issued by a law enforcement officer, traffic accident investigation officer, traffic infraction enforcement officer, or a member of the fire department at the scene of a fire, rescue operation, or other emergency situation, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1312', 
                title: 'False Report to Law Enforcement', 
                text: 'Any person who knowingly makes, transmits, or causes to be transmitted a false report, complaint, or statement to a law enforcement officer or agency, knowing such report to be false, with the intent to cause an investigation or response, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1313', 
                title: 'Escape', 
                text: 'Any prisoner confined in any prison, jail, road camp, or other penal institution, or being transported to or from a place of confinement, who escapes or attempts to escape from such confinement, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1314', 
                title: 'Evasion', 
                text: 'Any person who willfully flees or attempts to flee from a peace officer, provided that the officer is in uniform and has used their voice or emergency lights to signal or hail the person from a reasonable distance, shall be guilty of evasion and shall be guilty of a misdemeanor',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1315', 
                title: 'Resisting Arrest', 
                text: 'Any person who knowingly and willfully resists, obstructs, or opposes any law enforcement officer in the lawful performance of their official duties, including the lawful arrest or detention of such person or another person, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1316', 
                title: 'Obstruction of Conservation', 
                text: 'Any person who knowingly and willfully continuously interferes with the operations of Parks and Wildlife rangers, Parks Police, or any other employee of the Department of Interior whose duty involves conservation of nature in the performance of their lawful duties, despite having received one or more warnings, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
              { sec: '1 F.S.C. § 1317', 
                title: 'Obstruction of Emergency Services', 
                text: 'Any person who knowingly obstructs, hinders, or interferes with any emergency medical technician, paramedic, rescue technician, or firefighter in the performance of their official duties shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined'
              },
            ]
          },

          { name: 'Chapter IV - Commercial Offenses',
            provisions: [
              {
                sec: '1 F.S.C. § 1401', 
                title: 'Unlawful Operation of a Business', 
                text: 'Any person who knowingly establishes, conducts, manages, or operates any commercial enterprise, trade, or occupation for which a license, permit, or certificate of authority is required by State law or municipal ordinance, without first obtaining and maintaining a valid and current such license, or who continues to operate after such license has been lawfully suspended, revoked, or expired without reinstatement or renewal, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              {
                sec: '1 F.S.C. § 1402', 
                title: 'Commercial Fraud', 
                text: 'Any person who knowingly devises, executes, or participates in a scheme or artifice to defraud a commercial entity, customer, or partner, or to obtain money, property, or services by means of false pretenses, misrepresentation, or concealment of material fact shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
            ]
          },

          { name: 'Chapter V - Judicial Process Offenses',
            provisions: [
              {
                sec: '1 F.S.C. § 1501', 
                title: 'Contempt of Court', 
                text: 'Any person who knowingly engages in disorderly, contemptuous, or insolent behavior toward a judicial officer during court proceedings, or who willfully disobeys, resists, or obstructs any lawful order, process, or mandate issued by a court of competent jurisdiction shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              {
                sec: '1 F.S.C. § 1502', 
                title: 'Perjury', 
                text: 'Any person who makes a false sworn statement or affirmation in a judicial proceeding, including a trial, hearing, or deposition, regarding a material matter, with knowledge of its falsity and with the intent to deceive the court or affect the outcome of the proceeding, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              {
                sec: '1 F.S.C. § 1503', 
                title: 'Failure to Appear in Court', 
                text: 'Any person who, having been lawfully summoned or ordered to appear before a court of competent jurisdiction or a judicial officer, knowingly and willfully fails to appear at the designated date, time, and location, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 1504', 
                title: 'Violation of a Court Order', 
                text: 'Any person who knowingly and willfully violates, disregards, or fails to comply with any lawful order, injunction, or judgment issued by a court of competent jurisdiction shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 1505', 
                title: 'Tampering with a Juror', 
                text: 'Any person who knowingly communicates with, offers a benefit to, threatens, or intimidates a juror or prospective juror with the intent to influence, coerce, or corrupt their deliberations, verdict, or performance of official duties shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 1506', 
                title: 'Tampering with a Witness', 
                text: 'Any person who knowingly induces, attempts to induce, or causes another person to testify falsely, withhold testimony, evade legal process, or absent themselves from any official proceeding, by means of bribery, intimidation, threat, or coercion, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 1507', 
                title: 'Judicial Misconduct', 
                text: 'Any judicial officer who knowingly and willfully engages in conduct that constitutes a clear and substantial violation of judicial ethics, including bias, ex parte communications, abuse of discretion, or accepting unauthorized gifts or benefits from parties appearing before them, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 1508', 
                title: 'Impersonation of a Judicial Officer', 
                text: 'Any person who knowingly assumes, pretends to hold, or exercises the duties of a judge, magistrate, or other judicial officer without being duly appointed, commissioned, or authorized to do so, with the intent to deceive, intimidate, or obtain an unlawful benefit, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
            ]
          },

          { name: 'Chapter VI - Financial Crime Offenses',
            provisions: [
              {
                sec: '1 F.S.C. § 1601', 
                title: 'Money Laundering', 
                text: 'Any person who knowingly conducts, facilitates, or participates in a financial transaction, transfer, exchange, or series of transactions involving proceeds derived from any criminal activity, with the intent to conceal, disguise, or obscure the source, ownership, location, or nature of such proceeds, or to avoid a transaction reporting requirement, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              {
                sec: '1 F.S.C. § 1602', 
                title: 'Embezzlement', 
                text: 'Any person who, being an employee, officer, agent, fiduciary, or trustee of any person, entity, or organization, knowingly and fraudulently appropriates, converts, steals, or takes the money, funds, property, or assets entrusted to their care, custody, or control, for their own benefit or the benefit of another, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
            ]
          },
          
          { name: 'Chapter VII - Prohibited Items Offenses',
            provisions: [
              {
                sec: '1 F.S.C. § 1701', 
                title: 'Posession of Prohibited Items', 
                text: 'Any person who knowingly possesses, stores, or maintains any item, substance, or material that has been declared unlawful for private possession by State law, ordinance, or regulation shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              {
                sec: '1 F.S.C. § 1702', 
                title: 'Sale or Distribution of Prohibited Items', 
                text: 'Any person who knowingly sells, offers for sale, distributes, transfers, or otherwise makes available any item, substance, or material that has been declared unlawful for sale or distribution by State law, ordinance, or regulation shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              {
                sec: '1 F.S.C. § 1703', 
                title: 'Manufacture of Prohibited Items', 
                text: 'Any person who knowingly manufactures, produces, cultivates, or assembles any item, substance, or material that has been declared unlawful for manufacture or production by State law, ordinance, or regulation shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              {
                sec: '1 F.S.C. § 1704', 
                title: 'Transportation of Prohibited Items', 
                text: 'Any person who knowingly transports, carries, conveys, or causes to be transported any item, substance, or material that has been declared unlawful for transportation by State law, ordinance, or regulation shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
            ]
          },
        ],
      },

      {
        name: 'SUBTITLE 2 - OFFENSES AGAINST THE PLAYER',
        subchapters: [
          {
            name: 'Chapter I - Threat & Bodily Harm Offenses',
            provisions: [
              { 
                sec: '1 F.S.C. § 2101', 
                title: 'Assault', 
                text: 'Any person who knowingly attempts to cause, or intentionally, recklessly, or negligently causes bodily injury to another person, or who places another person in reasonable apprehension of imminent bodily injury, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2102', 
                title: 'Aggravated Assault', 
                text: 'Any person who knowingly causes serious bodily injury to another person, or who causes bodily injury to another person by means of a deadly weapon, dangerous instrument, or any other item capable of causing serious harm, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2103', 
                title: 'Battery', 
                text: 'Any person who knowingly and unlawfully makes physical contact of an insulting, provoking, or harmful nature with another person, or who intentionally causes bodily harm to another person, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2104', 
                title: 'Aggravated Battery', 
                text: 'Any person who knowingly causes great bodily harm, permanent disfigurement, or protracted loss or impairment of the function of any bodily member or organ to another person, or who causes such harm by means of a deadly weapon, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2105', 
                title: 'Threats', 
                text: 'Any person who knowingly and willfully threatens to commit a crime or act of violence against another person, or to cause bodily harm or property damage to another person, with the intent to terrorize, intimidate, or place such person in reasonable fear, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2106', 
                title: 'Harassment', 
                text: 'Any person who knowingly engages in a course of conduct directed at a specific person, including repeated communication, physical contact, or other behavior, that serves no legitimate purpose and causes substantial emotional distress to such person, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2107', 
                title: 'Reckless Endangerment', 
                text: 'Any person who knowingly engages in conduct that creates a substantial risk of serious bodily injury or death to another person, and who consciously disregards such risk, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2108', 
                title: 'Menacing', 
                text: 'Any person who knowingly and intentionally places another person in fear of imminent serious bodily injury or death by means of a threat, gesture, or display of a deadly weapon or dangerous instrument shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
            ],
          },
          
          {name: 'Chapter II - Homicide Offenses',
            provisions: [
              { sec: '1 F.S.C. § 2201', 
                title: 'First Degree Murder', 
                text: 'Any person who unlawfully and with malice aforethought, deliberate premeditation, and specific intent to kill causes the death of another person shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2202', 
                title: 'Second Degree Murder', 
                text: 'Any person who unlawfully and with malice aforethought, but without deliberate premeditation, causes the death of another person, including by acts indicating a depraved indifference to human life, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2203', 
                title: 'Manslaughter', 
                text: 'Any person who unlawfully causes the death of another person upon a sudden quarrel, in the heat of passion, or upon adequate provocation, without malice aforethought, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2204', 
                title: 'Involuntary Manslaughter', 
                text: 'Any person who unintentionally causes the death of another person through the commission of a lawful act that is performed in an unlawful manner, or through the commission of an unlawful act that is not a felony, or through gross negligence or reckless disregard for human life, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2205', 
                title: 'Negligent Homicide', 
                text: 'Any person who causes the death of another person through criminal negligence, including the failure to exercise reasonable care that a prudent person would exercise under similar circumstances, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2206', 
                title: 'Attempted Murder', 
                text: 'Any person who, with the specific intent to unlawfully cause the death of another person, commits an act or acts that constitute a substantial step toward the commission of such offense, but fails to cause the death of such person, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2207', 
                title: 'Vehicular Homicide', 
                text: 'Any person who, while operating a motor vehicle in a reckless, negligent, or unlawful manner, causes the death of another person shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
            ]
          },

          {name: 'Chapter III - Offenses Involving Deception and Fraud',
            provisions: [
              { sec: '1 F.S.C. § 2301', 
                title: 'Fraud', 
                text: 'Any person who knowingly devises, executes, or participates in a scheme, artifice, or course of conduct to defraud another person or to obtain money, property, services, or any other thing of value by means of false pretenses, misrepresentation, concealment of material fact, or deceptive practice shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2302', 
                title: 'Impersonation', 
                text: 'Any person who knowingly assumes the identity of another individual with the intent to deceive, defraud, or obtain a benefit, or to cause harm or loss to another person, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2303', 
                title: 'False Pretenses', 
                text: 'Any person who knowingly obtains money, property, or services from another person by means of false representation, false promise, or concealment of material fact, with the intent to defraud, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
            ]
          },

          {name: 'Chapter IV - Offenses Against Personal Rights & Dignity',
            provisions: [
              { sec: '1 F.S.C. § 2401', 
                title: 'Defamation', 
                text: 'Any person who knowingly and falsely communicates, publishes, or disseminates a statement concerning another person that is harmful to their reputation, with the intent to damage such person\'s standing in the community or to cause emotional distress, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2402', 
                title: 'Unlawful Surveillance', 
                text: 'Any person who knowingly and without authorization uses any device, instrument, or technology to observe, record, or monitor another person in a location where such person has a reasonable expectation of privacy shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
            ]
          },

          {name: 'Chapter V - Kidnapping & Related Offenses',
            provisions: [
              { sec: '1 F.S.C. § 2501', 
                title: 'Kidnapping', 
                text: 'Any person who knowingly and unlawfully confines, detains, restrains, or abducts another person against their will, without lawful authority, and who moves or transports such person a substantial distance from their original location, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2502', 
                title: 'Aggravated Kidnapping', 
                text: 'Any person who commits the offense of kidnapping and who additionally inflicts bodily harm upon the victim, threatens the victim with imminent serious bodily harm or death, holds the victim for ransom or reward, or uses the victim as a shield or hostage, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2503', 
                title: 'Attempted Kidnapping', 
                text: 'Any person who, with the specific intent to commit the offense of kidnapping, commits an act or acts that constitute a substantial step toward the commission of such offense, but fails to complete the kidnapping, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2504', 
                title: 'False Imprisonment', 
                text: 'Any person who knowingly and unlawfully restrains, confines, or detains another person without lawful authority and against their will, without moving or transporting such person a substantial distance, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 2505', 
                title: 'Aggravated False Imprisonment', 
                text: 'Any person who commits the offense of false imprisonment and who additionally inflicts bodily harm upon the victim, threatens the victim with imminent serious bodily harm, or confines the victim in a manner that creates a substantial risk of serious bodily injury or death, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
            ]
          },
        ]
      },

      {
        name: 'SUBTITLE 3 - OFFENSES AGAINST PROPERTY',
        subchapters: [
          {
            name: 'Chapter I - Theft, Damage to Property & Tresspass Offenses',
            provisions: [
              { 
                sec: '1 F.S.C. § 3101', 
                title: 'Theft', 
                text: 'Any person who knowingly and unlawfully takes, carries away, or exercises unauthorized control over the property of another with the intent to permanently deprive the owner thereof shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 3102', 
                title: 'Grand Theft', 
                text: 'Any person who knowingly and unlawfully takes, carries away, or exercises unauthorized control over the property of another, where the value of such property exceeds $10,000, with the intent to permanently deprive the owner thereof, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 3103', 
                title: 'Robbery', 
                text: 'Any person who, in the course of committing a theft, knowingly uses force, threatens the imminent use of force, or places any person in fear of immediate bodily injury shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 3104', 
                title: 'Burglary', 
                text: 'Any person who knowingly enters or remains unlawfully in a building, structure, or dwelling with the intent to commit a theft or any felony therein shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 3105', 
                title: 'Trespass', 
                text: 'Any person who knowingly enters or remains upon the property, premises, or dwelling of another after having been notified, by signage or verbal warning, that entry is forbidden or that they are to depart shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 3106', 
                title: 'Criminal Mischief', 
                text: 'Any person who knowingly and without lawful authority damages, destroys, defaces, or tampers with any property belonging to another, or who interferes with the use or enjoyment of such property, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 3107', 
                title: 'Aggravated Criminal Mischief', 
                text: 'Any person who knowingly and without lawful authority causes substantial damage, destruction, or impairment to the property of another, or who causes damage to property by means of fire, explosion, or hazardous material, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 3108', 
                title: 'Vandalism', 
                text: 'Any person who knowingly and without lawful authority damages, destroys, defaces, mars, marks, or otherwise injures the property of another person or entity, including any structure, vehicle, monument, signage, or natural feature, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 3109', 
                title: 'Arson', 
                text: 'Any person who knowingly and unlawfully sets fire to or burns any building, structure, dwelling, or property belonging to another, or who sets fire to any property with the intent to defraud an insurer, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
            ],
          }
        ]
      },

      {
        name: 'SUBTITLE 4 - OFFENSES INVOLVING FIREARMS',
        subchapters: [
          {
            name: 'Chapter I - Posession, Sale, Transfer & Distribution Offenses',
            provisions: [
              { 
                sec: '1 F.S.C. § 4101', 
                title: 'Unlawful Possession of a Firearm', 
                text: 'Any person who knowingly possesses, carries, stores, or maintains any firearm, as defined by State law, without being licensed, permitted, or otherwise authorized to do so, or in a manner prohibited by State law, ordinance, or regulation, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 4102', 
                title: 'Possession of a Firearm by a Prohibited Person', 
                text: 'Any person who knowingly possesses, carries, stores, or maintains any firearm, knowing that they have been convicted of a felony, adjudicated as delinquent, adjudicated mentally incompetent, or are otherwise prohibited by State or federal law from possessing a firearm, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 4103', 
                title: 'Possession of a Firearm in a Protected Location', 
                text: 'Any person who knowingly possesses, carries, or stores any firearm within the confines of a school, government building, courthouse, correctional facility, hospital, place of worship, or other protected location designated by State law, or within 1,000 feet thereof, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 4104', 
                title: 'Unlawful Sale or Transfer of a Firearm', 
                text: 'Any person who knowingly sells, gives, lends, leases, trades, or otherwise transfers a firearm to another person, without conducting a background check, without a valid license, or in a manner prohibited by State law, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 4105', 
                title: 'Sale or Transfer of a Firearm to a Prohibited Person', 
                text: 'Any person who knowingly sells, gives, lends, leases, trades, or otherwise transfers a firearm to any person who is prohibited by State or federal law from possessing a firearm, including a convicted felon, an adjudicated incompetent, or a minor, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 4106', 
                title: 'Sale or Transfer of a Firearm to a Prohibited Person', 
                text: 'Any person who knowingly sells, gives, lends, leases, trades, or otherwise transfers a firearm to any person who is prohibited by State or federal law from possessing a firearm, including a convicted felon, an adjudicated incompetent, or a minor, shall be guilty of a felony.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
            ],
          },
          {
            name: 'Chapter II - Use and Discharge Offenses',
            provisions: [
              { 
                sec: '1 F.S.C. § 4201', 
                title: 'Unlawful Use of a Firearm', 
                text: 'Any person who knowingly uses, displays, or threatens to use any firearm in a manner that creates a reasonable fear of harm or injury to another person, without lawful justification, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 4202', 
                title: 'Unlawful Discharge of a Firearm', 
                text: 'Any person who knowingly and without lawful authority discharges or fires any firearm in a public place, within the limits of any municipality, or in a reckless or negligent manner that creates a substantial risk of harm to persons or property, shall be guilty of a felony.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'FELONY',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 4203', 
                title: 'Brandishing a Firearm', 
                text: 'Any person who knowingly and without lawful authority displays, brandishes, or otherwise makes visible any firearm in a threatening, angry, or intimidating manner, or in a manner that causes another person to reasonably fear for their safety, shall be guilty of a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
            ],
          }
        ]
      },

      {
        name: 'SUBTITLE 5 - MISCELLANEOUS OFFENSES',
        subchapters: [
          {
            name: 'Chapter I - Inchoate & Party Liability Offenses',
            provisions: [
              { 
                sec: '1 F.S.C. § 5101', 
                title: 'Attempt to Commit a Crime', 
                text: 'Any person who, with the specific intent to commit a particular offense, performs any act that constitutes a substantial step toward the commission of such offense, but who fails to complete the commission of such offense, shall be guilty of an offense of the same classification as the crime attempted, except that an attempt to commit a felony shall be a felony and an attempt to commit a misdemeanor shall be a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 5102', 
                title: 'Criminal Conspiracy', 
                text: 'Any person who agrees, combines, or conspires with one or more other persons to commit any offense, and who takes a substantial step toward the commission of such offense, shall be guilty of an offense of the same classification as the crime conspired to commit, except that a conspiracy to commit a felony shall be a felony and a conspiracy to commit a misdemeanor shall be a misdemeanor.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 5103', 
                title: 'Solicitation to Commit a Crime', 
                text: 'Any person who knowingly commands, encourages, requests, or solicits another person to commit any offense, with the intent that such offense be committed, shall be guilty of an offense of the same classification as the crime solicited, except that solicitation to commit a felony shall be a felony and solicitation to commit a misdemeanor shall be a misdemeanor.',
                subsections: [],
                status: 'BY-CONVICTION',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
              { sec: '1 F.S.C. § 5104', 
                title: 'Accessory Before the Fact', 
                text: 'Any person who, being absent from the scene of a crime, knowingly aids, abets, counsels, commands, or procures the commission of such offense, with the intent to promote or facilitate the commission of such offense, shall be guilty of the same offense as the principal.',
                subsections: [],
                status: 'ACTIVE',
                crimeType: 'MISDEMEANOR',
                sentence: 'Sentence: Undefined',
              },
            ],
          }
        ]
      }
    ],
  },

  {
    name: 'Title 2 — Vehicle Code',
    color: '#7489a728',
    chapters: [
      {
        name: 'SUBTITLE 1 - OFFENSES RELATING TO MOTOR VEHICLES',
        subchapters: [
          {
            name: 'Chapter I - Traffic Violations',
            provisions: [
              { sec: '2 F.S.C. § 1101', 
                title: 'Careless Driving',
                text: 'Any person who operates a motor vehicle upon any public roadway in a careless or imprudent manner that endangers or is likely to endanger any person or property shall be guilty of an infraction.',
                subsections: [],
                crimeType: 'INFRACTION',
                status: 'ACTIVE',
                sentence: 'Sentence: Undefined',
              },
              { sec: '2 F.S.C. § 1102', 
                title: 'Reckless Driving',
                text: 'Any person who operates a motor vehicle upon any public roadway in a manner that demonstrates a willful and wanton disregard for the safety of persons or property shall be guilty of a misdemeanor.',
                subsections: [],
                crimeType: 'MISDEMEANOR',
                status: 'ACTIVE',
                sentence: 'Sentence: Undefined',
              },
              { sec: '2 F.S.C. § 1103', 
                title: 'Felony Reckless Driving',
                text: 'Any person who commits the offense of reckless driving and who additionally causes bodily injury to another person, causes substantial property damage, or operates a vehicle at a speed exceeding the posted limit by twenty miles per hour or more upon any public roadway shall be guilty of a felony.',
                subsections: [],
                crimeType: 'FELONY',
                status: 'ACTIVE',
                sentence: 'Sentence: Undefined',
              },
              { sec: '2 F.S.C. § 1104', 
                title: 'Speeding',
                text: 'Any person who operates a motor vehicle upon any public roadway at a speed in excess of the posted maximum speed limit shall be guilty of an infraction.',
                subsections: [],
                crimeType: 'INFRACTION',
                status: 'ACTIVE',
                sentence: 'Sentence: Undefined',
              },
              { sec: '2 F.S.C. § 1105', 
                title: 'Failure to Maintain Lanes',
                text: 'Any person who operates a motor vehicle upon any public roadway and fails to drive within a single lane, or who moves from such lane without first ascertaining that such movement can be made with reasonable safety, shall be guilty of an infraction.',
                subsections: [],
                crimeType: 'INFRACTION',
                status: 'ACTIVE',
                sentence: 'Sentence: Undefined',
              },
              { sec: '2 F.S.C. § 1106', 
                title: 'Failure to Yield to a Traffic Control Device or Sign',
                text: 'Any person who operates a motor vehicle upon any public roadway and fails to obey the directions of any traffic control signal, sign, or device, including stop signs and yield signs, shall be guilty of an infraction.',
                subsections: [],
                crimeType: 'INFRACTION',
                status: 'ACTIVE',
                sentence: 'Sentence: Undefined',
              },
              { sec: '2 F.S.C. § 1107', 
                title: 'Impeding Traffic',
                text: 'Any person who operates a motor vehicle upon any public roadway at a speed so slow as to impede the normal and reasonable movement of traffic, except when necessary for safe operation, shall be guilty of an infraction.',
                subsections: [],
                crimeType: 'INFRACTION',
                status: 'ACTIVE',
                sentence: 'Sentence: Undefined',
              },
              { sec: '2 F.S.C. § 1108', 
                title: 'Illegal Parking',
                text: 'Any person who parks, stops, or leaves a motor vehicle in any location where parking is prohibited by State law or local ordinance, including fire lanes, handicapped zones without a permit, and no-parking zones, shall be guilty of an infraction.',
                subsections: [],
                crimeType: 'INFRACTION',
                status: 'ACTIVE',
                sentence: 'Sentence: Undefined',
              },
              { sec: '2 F.S.C. § 1109', 
                title: 'Obstruction of Traffic',
                text: 'Any person who stops, parks, or leaves a motor vehicle in a manner that blocks, obstructs, or impedes the lawful flow of traffic upon any public roadway, including blocking intersections or roadways, shall be guilty of an infraction.',
                subsections: [],
                crimeType: 'INFRACTION',
                status: 'ACTIVE',
                sentence: 'Sentence: Undefined',
              },
            ]
          },
        ]
      },
    ]
  },

  {
    name: 'Title 3 — Management Mandates',
    color: '#eadde8',
    chapters: [
      {
        name: 'SUBTITLE 1 - GENERAL PROVISIONS',
        subchapters: [
          {
            name: 'Chapter I - Community Management Composition',
            provisions: [
              { 
                sec: '3 F.S.C. § 101', 
                title: 'Community Management of the State of Fairmont shall be comprised of the following people:',
                subsections: [
                  { sec: '(a)', text: 'SuperTrooper178, Community Executive' },
                  { sec: '(b)', text: 'h_oudinien, Community Management' },
                  { sec: '(c)', text: 'g_renaderskiy, Community Management'}
                ],
                status: 'ADMIN MANDATED'
              },
              { 
                sec: '3 F.S.C. § 102', 
                title: 'Community Management of the State of Fairmont shall be headed by the Community Executive	',
                subsections: [],
                status: 'ADMIN MANDATED'
              },
            ]
          },
          {
            name: 'Chapter II - Composition of the Office of the State Registrar',
            provisions: [
              { 
                sec: '2 F.S.C. § 201', 
                title: 'The Office of the State Registrar shall be comprised of the following people:',
                subsections: [
                  { sec: '(a)', text: '1onzok, State Registrar' },
                  { sec: '(b)', text: 'aw7y, Deputy State Registrar' },
                ],
                status: 'ADMIN MANDATED'
              },
            ]
          },
        ]
      },
    ]
  },
];